blank_issues_enabled: false
contact_links:
  - name: Project Guide (AGENTS.md)
    url: https://github.com/your-org/your-repo/blob/main/AGENTS.md
    about: Read the project overview, workflows, and coding guidelines.
